In [21]:
import numpy as np

In [22]:
arr1 = np.empty(shape=(4,5))
arr2 = np.empty(shape=(5,4))

In [23]:
arr1 = np.random.rand(4,5) * 100
arr2 = np.random.rand(5,4) * 100
arr2

array([[33.95092319, 82.9471703 , 78.43827495, 28.4734355 ],
       [54.74271063, 10.11831786, 77.5959952 , 34.58381528],
       [99.66476531, 98.74350492, 60.99683951, 99.94756959],
       [ 1.77794592, 19.41591733, 84.82923943, 39.51199933],
       [75.7962224 , 32.37682481, 85.36278968, 98.25132066]])

In [24]:
arr3 = np.matmul(arr1, arr2)
arr3

array([[21574.15620188, 20354.34946012, 25481.78968237, 22126.82480737],
       [19152.78233358, 19695.68811851, 24776.02810603, 18341.47631378],
       [11206.3789512 ,  9670.25694374, 15717.23941138, 14135.34329222],
       [13893.53960919, 11723.47320925, 13151.88489871, 15576.73296278]])

In [25]:
arr4 = np.random.rand(3,3)
arr5 = np.random.rand(3,3)
print(arr4)
print(arr5)
arr4*arr5

[[0.37277893 0.48889781 0.09303517]
 [0.03743921 0.79365299 0.12604055]
 [0.92608603 0.96244986 0.17664998]]
[[0.04827388 0.43213541 0.05266921]
 [0.19285636 0.91454248 0.7722755 ]
 [0.28254509 0.59755756 0.22693868]]


array([[0.01799548, 0.21127006, 0.00490009],
       [0.00722039, 0.72582937, 0.09733803],
       [0.26166106, 0.57511919, 0.04008871]])

In [26]:
mean = np.mean(a=arr1)
meadian = np.median(a=arr2)
print(mean, meadian)

53.07531341130583 68.39653095593732


In [27]:
t = arr4.T
t

array([[0.37277893, 0.03743921, 0.92608603],
       [0.48889781, 0.79365299, 0.96244986],
       [0.09303517, 0.12604055, 0.17664998]])

In [28]:
np.linalg.det(a=arr4)

np.float64(-0.004152534016308828)

In [29]:
arr1

array([[91.7606059 , 61.87867485, 95.48109269, 16.92946178, 72.89535007],
       [95.09676447, 94.43812765, 99.48441538, 35.92250416, 10.23007595],
       [11.00591714, 24.1226248 , 58.16955358, 63.39003679, 47.52243525],
       [ 1.63016041, 15.13702818, 96.12662494, 25.64513539, 44.63967885]])

In [30]:
arr1[: , 1:2]

array([[61.87867485],
       [94.43812765],
       [24.1226248 ],
       [15.13702818]])