In [2]:
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

np.int64(8)

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_arr=arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_arr[:]
slice_arr[:]=99
slice_arr
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy=arr.copy()
arr
arr_copy[:]=100
arr_copy
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d
arr_2d[0][0]
arr_2d[1]

array([20, 25, 30])

In [26]:
arr_2d[1,2]

np.int64(30)

In [29]:
arr_2d[:2,1:]
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
arr=np.arange(1,11)
arr
bool_arr=arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr<3]

array([1, 2])