In [1]:
list=[1,2,3]
import numpy as np
arr=np.array(list)

In [2]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand(5)

array([0.82195228, 0.57681726, 0.61613308, 0.05230135, 0.50681461])

In [10]:
np.random.rand(5,5)

array([[0.27994418, 0.53816634, 0.15982331, 0.23675479, 0.97588993],
       [0.44042054, 0.95339731, 0.24817518, 0.90008274, 0.37284139],
       [0.23175948, 0.11156886, 0.14096273, 0.65125905, 0.1559847 ],
       [0.59998636, 0.00980092, 0.37896499, 0.39115107, 0.01890621],
       [0.4779559 , 0.06379725, 0.25370702, 0.86809877, 0.55004606]])

In [12]:
np.random.randn(2)

array([0.84346451, 0.90209222])

In [13]:
np.random.randn(4,4)

array([[-0.69295352,  0.00426524,  0.4335873 ,  0.95901497],
       [-0.90947447, -0.01273596,  0.99776704, -1.59357597],
       [-0.50363275,  2.09475332, -1.27463036,  0.10783763],
       [ 0.59958288,  1.1441042 ,  0.65861574,  0.08366303]])

In [14]:
np.random.randint(1,100)

7

In [15]:
np.random.randint(1,100,11)

array([21, 10, 35, 33, 84, 73, 34, 97, 83, 64, 59])

In [16]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr=np.random.randint(0,50,10)
ranarr

array([27, 24, 24, 34, 18,  9, 26, 11, 12, 12])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.max()
ranarr.argmax()

np.int64(3)

In [27]:
ranarr.min()
ranarr.argmin()

np.int64(5)

In [29]:
arr=arr.reshape(5,5)
arr.shape

(5, 5)

In [30]:
arr.dtype

dtype('int64')

In [31]:
from numpy.random import randint
randint(2,10)

8