Perform all data preprocessing tasks and feature selection on "Exercise-CarData.csv"

A. Steps for Data Transformation

In [35]:
# Step 1: Import Libraries

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder,OneHotEncoder

In [36]:
# Step 2: Load Data
datasets=pd.read_csv('Exercise-CarData.csv')
print("\nData :\n",datasets)
print("\nData statistics\n",datasets.describe())


Data :
       Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weigh

In [37]:
# Step 3: Seprate Input and Output attributes
x=datasets.iloc[:,:-1].values
y=datasets.iloc[:,-1].values
print("\n\nInput : \n", x)
print("\n\nOutput: \n", y)



Input : 
 [[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


Output: 
 [1165 1165 1165 ... 1015 1015 1114]


In [38]:
x_new=datasets.iloc[:,1:3].values
print("\n\nX for transformation : \n", x_new)



X for transformation : 
 [[13500.    23.]
 [13750.    23.]
 [13950.    24.]
 ...
 [ 8500.    nan]
 [ 7250.    70.]
 [ 6950.    76.]]


In [39]:
# Step 4 : Perform scaling on age and salary
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x_new)
print("\n\nScaled X : \n", x_scaled)



Scaled X : 
 [[0.3250444  0.27848101]
 [0.3339254  0.27848101]
 [0.3410302  0.29113924]
 ...
 [0.14742451        nan]
 [0.10301954 0.87341772]
 [0.09236234 0.94936709]]


In [40]:
# Step 5 : Perform standardization on age and salary
std=StandardScaler()
x_std=std.fit_transform(x_new)
print("\n\nStandardized X : \n", x_std)



Standardized X : 
 [[ 0.76376268 -1.75818903]
 [ 0.83271485 -1.75818903]
 [ 0.88787659 -1.70437596]
 ...
 [-0.6152808          nan]
 [-0.96004167  0.7710253 ]
 [-1.04278428  1.09390373]]


B. Steps_for_Handling_Categorical_Data

In [41]:
# Step 4a: Apply LabelEncoder on the data
# to convert country names into numeric values
le = LabelEncoder()
x[ : ,0] = le.fit_transform(x[ : ,0])
print("\n\nInput : \n", x)



Input : 
 [[0 13500 23.0 ... 0 2000 'three']
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


In [42]:
onehotencoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Get the 'FuelType' column for one-hot encoding from the original datasets DataFrame
fuel_type_column = datasets['FuelType'].values.reshape(-1, 1)

# Fit and transform the 'FuelType' column
fuel_type_encoded = onehotencoder.fit_transform(fuel_type_column)

# Get feature names for the new one-hot encoded columns
fuel_type_feature_names = onehotencoder.get_feature_names_out(['FuelType'])

# Convert x (current numpy array) to a DataFrame temporarily to easily drop the original 'FuelType' column and concatenate new ones
# We need the column names to accurately drop by name
x_temp_df = pd.DataFrame(x, columns=datasets.columns[:-1])

print(f"Shape of x before One-Hot Encoding FuelType: {x_temp_df.shape}")

# Drop the original 'FuelType' column from the temporary DataFrame
x_temp_df = x_temp_df.drop('FuelType', axis=1)

# Create a DataFrame from the one-hot encoded FuelType array
fuel_type_encoded_df = pd.DataFrame(fuel_type_encoded, columns=fuel_type_feature_names, index=x_temp_df.index)

# Concatenate the modified x_temp_df with the one-hot encoded FuelType DataFrame
x = pd.concat([x_temp_df, fuel_type_encoded_df], axis=1).values

print(f"Shape of x after One-Hot Encoding FuelType: {x.shape}")
print("\nOne-Hot Encoded Input (x) with FuelType:\n", x)

Shape of x before One-Hot Encoding FuelType: (1436, 10)
Shape of x after One-Hot Encoding FuelType: (1436, 13)

One-Hot Encoded Input (x) with FuelType:
 [[0 13500 23.0 ... 1.0 0.0 0.0]
 [1 13750 23.0 ... 1.0 0.0 0.0]
 [2 13950 24.0 ... 1.0 0.0 0.0]
 ...
 [1433 8500 nan ... 0.0 1.0 0.0]
 [1434 7250 70.0 ... 0.0 0.0 1.0]
 [1435 6950 76.0 ... 0.0 1.0 0.0]]
