Steps for Data Transformation

In [1]:
# Step 1: Import Libraries

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [3]:
# Step 2: Load Data
datasets=pd.read_csv('Data_for_Transformation.csv')
print("\nData :\n",datasets)


Data :
     Country  Age  Salary Purchased
0    France   44   72000        No
1     Spain   27   48000       Yes
2   Germany   30   54000        No
3     Spain   38   61000        No
4   Germany   40   68000       Yes
5    France   35   58000       Yes
6     Spain   39   52000        No
7    France   48   79000       Yes
8   Germany   50   83000        No
9    France   37   67000       Yes
10    Spain   45   55000        No


In [7]:
# Step 3: Seprate Input and Output attributes
x=datasets.iloc[:,:-1].values
y=datasets.iloc[:,-1].values
print("\n\nInput : \n", x)
print("\n\nOutput: \n", y)



Input : 
 [['France' 44 72000]
 ['Spain' 27 48000]
 ['Germany' 30 54000]
 ['Spain' 38 61000]
 ['Germany' 40 68000]
 ['France' 35 58000]
 ['Spain' 39 52000]
 ['France' 48 79000]
 ['Germany' 50 83000]
 ['France' 37 67000]
 ['Spain' 45 55000]]


Output: 
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No']


In [8]:
x_new=datasets.iloc[:,1:3].values
print("\n\nX for transformation : \n", x_new)



X for transformation : 
 [[   44 72000]
 [   27 48000]
 [   30 54000]
 [   38 61000]
 [   40 68000]
 [   35 58000]
 [   39 52000]
 [   48 79000]
 [   50 83000]
 [   37 67000]
 [   45 55000]]


In Step 3, we separate the dataset into two parts: x represents the input features (all columns except the last one), and y represents the output or target variable (the last column). This is a common practice in machine learning, where x is used to train a model to predict y.

The `iloc` function in pandas is used for **integer-location based indexing**. It allows you to select data by its integer position.

In the line `x=datasets.iloc[:,:-1].values`:

*   `datasets` is your DataFrame.
*   `iloc` is called on the DataFrame to select data by integer location.
*   `:` before the comma means 'select all rows'.
*   `:-1` after the comma means 'select all columns except the last one'.
*   `.values` converts the selected data into a NumPy array.

So, `x` will contain all rows and all columns from the `datasets` DataFrame, excluding the very last column, converted into a NumPy array.

In [12]:
# Step 4 : Perform scaling on age and salary
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x_new)
print("\n\nScaled X : \n", x_scaled)



Scaled X : 
 [[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739 0.57142857]
 [0.34782609 0.28571429]
 [0.52173913 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]
 [0.7826087  0.2       ]]


In Step 4, we perform Min-Max Scaling on the 'Age' and 'Salary' columns. This technique transforms the data so that all values fall within a specific range, usually between 0 and 1. This is useful for machine learning algorithms that are sensitive to the magnitude of features, ensuring that no single feature dominates due to its larger scale.

In [13]:
# Step 5 : Perform standardization on age and salary
std=StandardScaler()
x_std=std.fit_transform(x_new)
print("\n\nStandardized X : \n", x_std)



Standardized X : 
 [[ 0.68188156  0.79548755]
 [-1.81835082 -1.41513049]
 [-1.37713334 -0.86247598]
 [-0.2005534  -0.21771238]
 [ 0.09359159  0.42705121]
 [-0.64177088 -0.49403964]
 [-0.05348091 -1.04669415]
 [ 1.27017153  1.44025115]
 [ 1.56431652  1.80868749]
 [-0.34762589  0.33494213]
 [ 0.82895405 -0.77036689]]


In Step 5, we perform Standardization on the 'Age' and 'Salary' columns. This technique transforms the data so that it has a mean of 0 and a standard deviation of 1. This is particularly useful for algorithms that assume normally distributed data or that are sensitive to the scale of features, helping to improve their performance and prevent features with larger values from disproportionately influencing the model.

Standardization takes your data and scales it so that its average is 0 and its spread (standard deviation) is 1. Imagine shifting all your data so the center is at zero, and then squishing or stretching it so most values fall neatly around that center.

Why do we do this?

Fair Play for Features: It makes sure that features with big numbers (like 'Salary') don't unfairly influence a machine learning model more than features with small numbers (like 'Age'). Everyone gets an equal voice!
Algorithm Harmony: Many machine learning algorithms work best when data is standardized, leading to better and faster results.
Better with Outliers: It's often more robust to extreme values (outliers) compared to other scaling methods because it doesn't force everything into a fixed range.